### ISSUE TITLE
Error "Invertor is not online:"

### ISSUE THREAD

**Issue by keeshelpt** [zonoskar/Goodwe2PVoutput#4]
Since may 16 I have a problem
=========================================
Response from Goodwe does not contain all data (len=17) : ['1', 'Normal', 'my-SN# ', '', '3345W', '9.9KWh', '5021.1KWh', '5084h', '', '224.1V/147.8V', '9.6A/9.2A', '244.2/0.0/0.0V', '13.8/0.0/0.0A', '49.98/0.00/0.00HZ', '44.4\xe2\x84\x83', '0.0KWh', '0.0KWh']
Parse data Error: list index out of range
Inverter is not online: 1 My-SN#  Normal 0.0 0.0 0.0 0.0  0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
sleep 600.0 seconds before next sample
=========================================
Instead of the timestamp there is an "Invertor is not online:" message.
The other data seems ok for example 3345W and 9,9KWh etc.

Can you help me?

BTW: 
On http://www.goodwe-power.com is a message:
"Dear Customers:
This local server for the customers in Oceania region is available now.
In the meanwhile, Goodwe is preparing another data server in Europe which shall be online next month.
Goodwe is working hard to deliver the better product features to the market and appreciate support from our customers."

I'm in Europe. Could this be a reason?

regards,
Kees

**Comment by zonoskar** [comment]
Hi Kees,
I think the problem is the weird characters in the last part (\xe2 \x84 and \x83). I'm pretty sure I have not accounted for input like that. If you go to the goodwe website, what does the realtime tab say? Does it also list those characters? It should be in the Temperature value.

Unfortunately, my inverter is a bit broken and stuck in non-wifi mode, so I'm unable to test on my own system. I also don't know if I'm getting the same problem as it has been that way for a few weeks now. I did receive a replacement part to fix it, so hopefully I can start logging again soon. Then I will also try to move to the EU server, but I suspect the only change needed is to change the server URL in the config file.

Cheers, Dennis.

**Comment by keeshelpt** [comment]
The temp.value is ok. See screenshot
![image](https://user-images.githubusercontent.com/26898578/40177769-caaa4c3e-59df-11e8-9fff-af89d903cc90.png)
I'm using WIFI mode.

Cheers,
Kees

**Comment by keeshelpt** [comment]
In https://www.utf8-chartable.de/unicode-utf8-table.pl?start=8448&number=128&names=-&utf8=string-literal

You can see  \xe2\x84\x83  is ℃

U+2103 | ℃ | \xe2\x84\x83

**Comment by zonoskar** [comment]
Hi Kees,

I see that the script expects 21 lines from the goodwe site, you get only 17. So apparently some data was dropped.

You could try to change the number 21 to 17 in the goodweData.py file. And put a # in front of the 4 lines following the comment "#Values that I'm not using (or don't know what they are" Apparently, those 4 values were dropped (Vbattery, Ibattery, SoC and Load).

Dennis.

**Comment by zonoskar** [comment]
If you update the script, it should have the changes I mentioned. Although I have not tested this so don't overwrite your existing directory.

Dennis.

**Comment by keeshelpt** [comment]
Done, see results below

Parse data Error: list index out of range
Buffering: S/N: My-SN# P:3047.0 E:17.1 V:389.9
sleep 240.0 seconds before next sample
^CTraceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/pi/Goodwe2PVoutput/__main__.py", line 83, in <module>
    mainloop( goodwe, pvoutput, csv, process)
  File "/home/pi/Goodwe2PVoutput/__main__.py", line 39, in mainloop
    time.sleep(interval)
KeyboardInterrupt

**Comment by zonoskar** [comment]
Ok, I see where I screwed up. Did you download the latest version, or make the changes yourself? The latest version should work now (famous last words).

In goodweData.py, the set_consume_day() should use index 15 and set_consume_total() should use 16.

Dennis.

**Comment by keeshelpt** [comment]
Ok, solved.

Tnx for help.

Cheers, 
Kees

**Comment by zonoskar** [comment]
Ok, you also thanks for trying.
