### ISSUE TITLE
Error retrieving data goodie site.

### ISSUE THREAD

**Issue by X-gen76** [zonoskar/Goodwe2PVoutput#6]
After installing the script and starting it I get the error below:

Error Page
Response from Goodwe does not contain all data (len=0) : []
Parse data Error: list index out of range
Inverter is not online:     0.0 0.0 0.0 0.0  0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0

Support would be appreciated.
This is the first time that i'm trying to use this script.

**Comment by zonoskar** [comment]
Hi,
Thanks for using my script. The error suggests there's no data from goodwe. Did you configure your setup correctly?

Dennis

________________________________

**Comment by X-gen76** [comment]
Made a typo in the system_id. This is working now. 

Another question i don't know if you can help me with that.
Is it possible to run the command `python -m Goodwe2PVoutput` constantly on the background on RPI? In case for example if the RPI is rebooted it will automatically start and keeps running the command.

**Comment by zonoskar** [comment]
Good to hear. You could try one of the methods at https://www.dexterindustries.com/howto/run-a-program-on-your-raspberry-pi-at-startup/

Cheers, Dennis.
